const items = [
    {
        id: '001',
        image: 'images/9.avif',
        company: 'Powerlook',
        item_name: 'sky Grey Rib Knit India Slim Casual Shirt',
        original_price: 1799,
        current_price: 1169,
        discount_percentage: 35,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 4.0,
            count: 500,
        },
    },
    {
        id: '002',
        image: 'images/10.jpg',
        company: 'sparx',
        item_name: 'Men white sneakers',
        original_price: 849,
        current_price: 764,
        discount_percentage: 10,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 3.9,
            count: 200,
        },
    },
    {
        id: '003',
        image: 'images/11.jpg',
        company: 'Rolex',
        item_name: 'Mesh Strap All Black Avatar Day and Date Functioning Quartz Analog Watch - For Men LS2917',
        original_price: 59999,
        current_price: 45999,
        discount_percentage: 23,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 4.8,
            count: 5205,
        },
    },
    {
        id: '004',
        image: 'images/12.avif',
        company: 'Voyage',
        item_name: 'Unisex Wayfarer Sunglasses With Polarised and UV Protected Lens 20089PMG4448Z',
        original_price: 3000,
        current_price: 1099,
        discount_percentage: 63,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 4.5,
            count: 690,
        },
    },
    
    {
        id: '005',
        image: 'images/5.jpg',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'images/6.jpg',
        company: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: 'images/7.jpg',
        company: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'images/8.jpg',
        company: 'Nivea',
        item_name: 'Men Fresh Deodrant 150ml',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '009',
        image: 'images/1.jpg',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '010',
        image: 'images/2.jpg',
        company: 'CUKOO',
        item_name: 'Women Padded Halter Neck Swimming Dress',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '011',
        image: 'images/3.jpg',
        company: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '012',
        image: 'images/4.jpg',
        company: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '013',
        image: 'images/13.jpg',
        company: 'Park Avenue',
        item_name: 'Park Avenue Conquer | Eau De Parfum Men, 100ml',
        original_price: 749,
        current_price: 449,
        discount_percentage: 40,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 4.0,
            count: 148,
        },
    },
    {
        id: '014',
        image: 'images/14.webp',
        company: 'Roadster',
        item_name: 'Men Striped Round Neck Pure Cotton Red T-Shirt',
        original_price: 799,
        current_price: 200,
        discount_percentage: 74,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 3.8,
            count: 593,
        },
    },
    {
        id: '015',
        image: 'images/15.jpg',
        company: 'Anand',
        item_name: 'Men Slim Fit Solid Mandarin Collar Casual Shirt',
        original_price: 1499,
        current_price: 399,
        discount_percentage: 73,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 3.9,
            count: 586,
        },
    },
    {
        id: '016',
        image: 'images/16.jpg',
        company: 'PROVOGUE',
        item_name: 'Men Casual, Evening/Party, Formal, Travel Maroon Genuine Leather RFID Wallet (8 Card Slots)',
        original_price: 1499,
        current_price: 349,
        discount_percentage: 76,
        return_period: 14,
        delivery_date: '14 Feb 2024',
        rating: {
            stars: 4,
            count: 5108,
        },
    }
];

export default items;